*.grid-columns: 4
classes: {
  diagram desc: {
    style.font-color: "gray"
    shape: text
  }
  external: {
    style.stroke: "red"
    tooltip: Предоставляется провайдером
  }
}

overall desc: |md
  # Диаграмма C4
| {
  class: diagram desc
  near: top-right
}

sys ctx: Системный Контекст {
  class: diagram desc
  near: top-center
}

provve: {
  *.grid-rows: 5
  Контейнеры.class: diagram desc

  back: {
    Компоненты.class: diagram desc

    notification: {
      desc: |md Управление уведомлениями и e-mail рассылками. |
    }
    validation: {
      desc: |md Прием решений, расчёт итоговых результатов. |
    }
    payment: {
      desc: |md Интеграция с платежным шлюзом, обработка заявок на оплату. |
    }
    skill: {
      desc: |md Оперирование навыками, экзаменами и голосованиями (отдаёт команды другим модулям по результату голосования). |
    }
    api: {
      desc: |md Лицо системы. Обработка запросов верхнего уровня, распределение на подзадачи отдельным модулям, без встроенной бизнес-логики. |
    }
    account: {
      desc: |md Оперирование аккаунтами, разграничение доступа. |
    }
  }

  antifraud: {
    Компоненты.class: diagram desc

    api: {
      desc: |md Логика взаимодействия с Provve. |
    }
    core: {
      desc: |md
        1. Наблюдение за прохождением экзамена.
        1. Загрузка наблюдений в Provve.
      |
    }
  }

  web: {
    Компоненты.class: diagram desc

    Svelte App: {
      desc: |md
        Фронтенд для больших мониторов.
      |
    }
    Docusaurus: {
      desc: |md
        Документация.
      |
    }
  }

  pg: PostgreSql {
    desc: |md
      Хранит:
      1. Информацию об голосованиях и экзаменах.
      1. Комментарии.
    |
    class: external
  }
  s3: S3 {
    desc: |md
      Хранит изображения и бинарники с материалами экзаменов.
    |
    class: external
  }
  docker: Docker {
    desc: |md
      На Docker запускаются контейнеры для проверки решения экзамена.
    |
    class: external
  }
  payment gateway: Платёжный шлюз {
    desc: |md
      1. Списание средств.
      1. Оповещение Provve о статусе платажей.
    |
    class: external
  }
}

сайт вакансий: {
  desc: |md xx.ru|
}

работадатель: {
  shape: c4-person
}

разработчик: {
  shape: c4-person
}

# Использование системы пользователями
разработчик -- provve: 1) проходит экзамен и получает результат
разработчик -> сайт вакансий: 2) указывает ссылку на реузльтат в резюме
разработчик -> работадатель: или 2) отправляет ссылку на результат в ЛС

работадатель <- сайты вакансий: 4) отбирает резюме с указанной ссылкой на результат экзамена
работадатель <- provve: 5) переходит по ссылке и видит страницу с результатом
