import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  users: [{type: 'autogenerated', dirName: 'users'}],
  devs: [{type: 'autogenerated', dirName: 'devs'}],
};

export default sidebars;
